{"name": "test_multiple_assert", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n2 Failed Assumptions:\n\ntest_assume.py:5: AssumptionFailure\n>>\tpytest.assume(1==2)\nAssertionError: assert False\n\ntest_assume.py:6: AssumptionFailure\n>>\tpytest.assume(3==4)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               2 Failed Assumptions:\nE               \nE               test_assume.py:5: AssumptionFailure\nE               >>\tpytest.assume(1==2)\nE               AssertionError: assert False\nE               \nE               test_assume.py:6: AssumptionFailure\nE               >>\tpytest.assume(3==4)\nE               AssertionError: assert False\n\n..\\..\\..\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\six.py:702: FailedAssumption"}, "start": 1597110650197, "stop": 1597110651535, "uuid": "87787955-5ca1-463c-b9c3-cb2759074c26", "historyId": "7d69a20c2b6c730750e7f569c6e98b68", "testCaseId": "acf18e1464e380ceaa7b356e804718b0", "fullName": "test_assume#test_multiple_assert", "labels": [{"name": "suite", "value": "test_assume"}, {"name": "host", "value": "user-PC"}, {"name": "thread", "value": "18200-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_assume"}]}