{"name": "test_add[3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4\n  +3\n  -4", "trace": "x = 3\n\n    @pytest.mark.parametrize('x',[(1),(2),(3)])\n    def test_add(x):\n>       assert x == random.randrange(1,7)\nE       assert 3 == 4\nE         +3\nE         -4\n\ntest_mark_parametrize.py:11: AssertionError"}, "parameters": [{"name": "x", "value": "3"}], "start": 1596104133515, "stop": 1596104133516, "uuid": "c94e4d5e-5dc8-4174-9825-eb2028ddb5e3", "historyId": "21615e291afbb84eb96a874a2b9b63c9", "testCaseId": "0ced0d8e21e7239fdc59fff1b3a3b804", "fullName": "test_mark_parametrize#test_add", "labels": [{"name": "suite", "value": "test_mark_parametrize"}, {"name": "host", "value": "user-PC"}, {"name": "thread", "value": "15028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_mark_parametrize"}]}